version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: pizzma-dev
    environment:
      MONGO_INITDB_DATABASE: pizzma-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db